/////////////////////////////////////////////////////////////////////////////////
//
//  Copyright (C) 2024- Equinor ASA
//
//  ResInsight is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ResInsight is distributed in the hope that it will be useful, but WITHOUT ANY
//  WARRANTY; without even the implied warranty of MERCHANTABILITY or
//  FITNESS FOR A PARTICULAR PURPOSE.
//
//  See the GNU General Public License at <http://www.gnu.org/licenses/gpl.html>
//  for more details.
//
/////////////////////////////////////////////////////////////////////////////////
/// @file
/// @brief One editable field entry displayed in the Quick Access panel.

#pragma once

#include "RimNamedObject.h"

#include "cafPdmChildField.h"
#include "cafPdmField.h"
#include "cafPdmObject.h"
#include "cafPdmProxyValueField.h"

class RimFieldReference;

//==================================================================================================
/// @brief Presents a referenced PDM field together with navigation and removal actions.
///
/// The referenced field remains owned by its source model object. This object owns only the
/// serializable RimFieldReference describing that relationship. Removal is deliberately deferred:
/// the button marks the entry and schedules a Quick Access rebuild, allowing the current property
/// editor callback to finish before the collection deletes the entry.
//==================================================================================================
class RimFieldQuickAccess : public caf::PdmObject
{
    CAF_PDM_HEADER_INIT;

public:
    /// Creates an empty entry and its owned field-reference object.
    RimFieldQuickAccess();

    /// Changes the non-owning field represented by this entry.
    void                 setField( caf::PdmFieldHandle* field );
    /// @return The currently resolved field, or `nullptr` if its object or keyword is no longer valid.
    caf::PdmFieldHandle* field() const;

    /// @return Whether the user requested removal during the current editor interaction.
    bool markedForRemoval() const;

    /// Selects the referenced field's owner in the main project property editor.
    void onSel();

private:
    /// Handles proxy-button changes generated by property editors.
    void fieldChangedByUi( const caf::PdmFieldHandle* changedField, const QVariant& oldValue, const QVariant& newValue ) override;
    /// Inserts the live referenced field and action buttons into a Quick Access group.
    void defineUiOrdering( QString uiConfigName, caf::PdmUiOrdering& uiOrdering ) override;
    /// Connects proxy tool-button editors to their callbacks.
    void defineEditorAttribute( const caf::PdmFieldHandle* field, QString uiConfigName, caf::PdmUiEditorAttribute* attribute ) override;

    /// Navigates to the object that owns the referenced field.
    void onSelectObjectButton();
    /// Marks this entry for deferred removal and requests a panel refresh.
    void onRemoveObjectButton();

private:
    /// Owned, serializable description of the non-owning field relationship.
    caf::PdmChildField<RimFieldReference*> m_fieldReference;

    /// Transient proxy backing the select-owner tool button.
    caf::PdmProxyValueField<bool> m_selectObjectButton;
    /// Transient proxy backing the remove-entry tool button.
    caf::PdmProxyValueField<bool> m_removeItemButton;

    /// Deferred-deletion flag consumed by RimQuickAccessCollection during rebuilding.
    bool m_markedForRemoval;
};
